import Foundation

public enum FakeAgentError: Error, Equatable, Sendable {
    case invalidUTF8
    case malformedCaptureLine(line: Int, content: String)
}

/// Generates the complete Swift source of a fake `ds4-agent` from a committed
/// NDJSON capture (mirrors `FakeServerSource` for the agent wire). The fake
/// validates its argv strictly (including `--workspace` and `--shell`), reads
/// one prompt line per turn from stdin, replays the capture to stdout with
/// `ts`-derived delays, and honors an ETX byte (0x03) on stdin as an
/// interrupt: it emits the documented interrupted `finish` when a tool block
/// is open, then `status idle`, then `ready`, and stops the turn. `FAKE_SPEED`
/// (0 = no delay) keeps the equivalence test fast; `FAKE_MIN_LINE_DELAY`
/// (seconds floor) gives the interrupt test a deterministic window.
public enum FakeAgentSource {

    public static func generate(capture: Data, engineArgv: [String]) throws -> String {
        guard
            let captureText = String(data: capture, encoding: .utf8)?
                .replacingOccurrences(of: "\r\n", with: "\n")
                .replacingOccurrences(of: "\r", with: "\n")
        else {
            throw FakeAgentError.invalidUTF8
        }

        var captureLines = captureText.split(separator: "\n", omittingEmptySubsequences: false)
        if captureLines.last == "" { captureLines.removeLast() }

        // Every event carries a monotonic `ts` (fork divergence #7); derive
        // per-line delays from consecutive deltas — no sidecar file needed.
        // The first line's delay is 0 (no wait before hello), mirroring
        // FakeServerSource's `lastStamp = stamps.first ?? 0`.
        var replay: [(Int, String)] = []
        var lastTS: Int?
        for (index, line) in captureLines.enumerated() {
            let trimmed = line.trimmingCharacters(in: .whitespacesAndNewlines)
            if trimmed.isEmpty { continue }
            guard let ts = extractTS(from: trimmed) else {
                throw FakeAgentError.malformedCaptureLine(line: index + 1, content: trimmed)
            }
            let delay = lastTS.map { max(0, ts - $0) } ?? 0
            lastTS = ts
            replay.append((delay, String(line)))
        }
        guard !replay.isEmpty else {
            throw FakeAgentError.malformedCaptureLine(line: 0, content: "<empty capture>")
        }

        let argvLiteral = engineArgv.map(FakeServerSource.swiftStringLiteral).joined(separator: ", ")
        let replayLiteral = replay
            .map { "    (\($0.0), \(FakeServerSource.swiftStringLiteral($0.1)))" }
            .joined(separator: ",\n")

        // Raw string template: `\(...)` inside is literal for the generated
        // file; only __ARGV__ / __REPLAY__ are filled.
        let template = #"""
import Foundation
import Darwin

// GENERATED by SwiftStarKit.FakeAgentSource — do not hand-edit.
// Regenerate from the committed capture; a drift test pins this.

let expectedArgv: [String] = [__ARGV__]
let replay: [(Int, String)] = [
__REPLAY__
]

func validateArgv() -> Bool {
    let actual = Array(CommandLine.arguments.dropFirst())
    return actual == expectedArgv
}

if !validateArgv() {
    FileHandle.standardError.write(Data("fake ds4-agent: argv mismatch; expected \(expectedArgv) got \(Array(CommandLine.arguments.dropFirst()))\n".utf8))
    exit(1)
}

let speed = Double(ProcessInfo.processInfo.environment["FAKE_SPEED"] ?? "1.0") ?? 1.0
let minDelay = Double(ProcessInfo.processInfo.environment["FAKE_MIN_LINE_DELAY"] ?? "0") ?? 0

func lineDelay(_ micros: Int) -> TimeInterval {
    max(minDelay, Double(micros) / 1_000_000 / max(speed, 0.0001))
}

func emit(_ line: String) {
    FileHandle.standardOutput.write(Data((line + "\n").utf8))
}

// Non-blocking probe: is an ETX (0x03) byte pending on stdin?
func etXPending() -> Bool {
    var p = pollfd(fd: STDIN_FILENO, events: Int16(POLLIN), revents: 0)
    guard poll(&p, 1, 0) > 0 else { return false }
    var b: UInt8 = 0
    return read(STDIN_FILENO, &b, 1) == 1 && b == 0x03
}

// Blocking read of one stdin line (raw bytes; stdio buffering would hide an
// ETX written right after the prompt's newline).
func readPromptLine() -> String? {
    var line = [UInt8]()
    while true {
        var p = pollfd(fd: STDIN_FILENO, events: Int16(POLLIN), revents: 0)
        guard poll(&p, 1, -1) > 0 else { return nil }
        var b: UInt8 = 0
        guard read(STDIN_FILENO, &b, 1) == 1 else { return nil }
        if b == 0x0A { break }
        line.append(b)
    }
    return String(decoding: line, as: UTF8.self)
}

var blockOpen = false

// The engine's documented ETX behavior (json-events.md / divergence #2) plus
// the D12 turn-outcome fields: interrupted finish when mid-block, then
// idle, then a turn-end ready carrying the interrupt stop reason.
func emitInterrupt() {
    if blockOpen {
        emit("{\"t\":\"tool\",\"phase\":\"finish\",\"idx\":0,\"calls\":1,\"status\":\"[tool call interrupted]\\n\",\"ts\":0}")
    }
    emit("{\"t\":\"status\",\"state\":\"idle\",\"prefill_done\":0,\"prefill_total\":0,\"prefill_tps\":0.0,\"generated\":0,\"gen_tps\":0.0,\"ctx_used\":0,\"ctx_size\":0,\"power\":100,\"error\":\"\",\"ts\":0}")
    emit("{\"t\":\"ready\",\"stop_reason\":\"interrupt\",\"generated\":0,\"ctx_used\":0,\"ts\":0}")
}

func replayOnce() {
    for (micros, line) in replay {
        if speed > 0 { Thread.sleep(forTimeInterval: lineDelay(micros)) }
        if etXPending() { emitInterrupt(); return }
        emit(line)
        if line.contains("\"phase\":\"start\"") { blockOpen = true }
        if line.contains("\"phase\":\"finish\"") { blockOpen = false }
    }
}

while readPromptLine() != nil {
    replayOnce()
}
"""#

        return template
            .replacingOccurrences(of: "__ARGV__", with: argvLiteral)
            .replacingOccurrences(of: "__REPLAY__", with: replayLiteral)
    }

    /// Extracts the monotonic µs `ts` from a wire line. `ts` is the last field
    /// on every event, and the JSON escaper escapes quotes inside string
    /// bodies, so a bare `"ts":<digits>` occurs only as the real field.
    private static func extractTS(from line: String) -> Int? {
        guard let range = line.range(of: #""ts":(\d+)"#, options: .regularExpression) else { return nil }
        let digits = line[range].dropFirst(5)  // drop `"ts":`
        return Int(digits)
    }
}
