import Foundation

/// Generates the complete Swift source of a fake host *app* (the tool owner)
/// from a canned-answer map. Mirrors `FakeAgentSource`/`FakeServerSource` for
/// the bidirectional wire (D4): the integration tier runs fake-agent ↔
/// fake-app end to end — the fake agent emits `tool_request` lines, the fake
/// app answers each with a `tool_result` line. The fake reads NDJSON lines on
/// stdin; a `tool_request` is answered with `ok:true` and the answer keyed by
/// the tool name, or `ok:false` and `refusal` when the name is unkeyed. Non-
/// `tool_request` lines (the agent's hello/status/text/ready stream) are
/// skipped — the app only owns the tool dispatch. Deterministic: answers are
/// sorted by key and the refusal is fixed, so the same map yields the same
/// source. Reuses `FakeServerSource.swiftStringLiteral` to embed the answers as
/// Swift string literals (the shared escaper for generated sources).
public enum FakeAppSource {

    /// The fixed refusal text for an unkeyed tool name (`ok:false`). Exposed so
    /// the integration tier can assert the refused `s` without re-deriving it.
    public static let refusal = "refused: no canned answer for this tool"

    /// Generates the fake app source. `answers` keys tool names to canned
    /// result text; an unkeyed name is answered with `ok:false` and `refusal`.
    public static func generate(answers: [String: String]) -> String {
        // Sort by key so the caller's insertion order cannot leak into the
        // source (determinism). The literal includes the enclosing brackets:
        // `[:]` for an empty map, or `["k": "v", …]` otherwise. The template
        // substitutes the whole literal (no extra brackets).
        let answersLiteral: String
        if answers.isEmpty {
            answersLiteral = "[:]"
        } else {
            let body = answers
                .sorted(by: { $0.key < $1.key })
                .map {
                    "\(FakeServerSource.swiftStringLiteral($0.key)): \(FakeServerSource.swiftStringLiteral($0.value))"
                }
                .joined(separator: ", ")
            answersLiteral = "[\(body)]"
        }
        let refusalLiteral = FakeServerSource.swiftStringLiteral(refusal)

        let template = #"""
import Foundation
import Darwin

// GENERATED by SwiftStarKit.FakeAppSource — do not hand-edit.
// The fake host app: reads `tool_request` lines on stdin, answers each with a
// `tool_result` line (ok:true + the canned answer keyed by name, or ok:false +
// the fixed refusal when the name is unkeyed). Non-request lines are skipped.

let answers: [String: String] = __ANSWERS__
let refusal = __REFUSAL__

// Blocking read of one stdin line (raw bytes; stdio buffering would hide a
// result the agent needs immediately after the request's newline).
func readStdinLine() -> String? {
    var line = [UInt8]()
    while true {
        var p = pollfd(fd: STDIN_FILENO, events: Int16(POLLIN), revents: 0)
        guard poll(&p, 1, -1) > 0 else { return nil }
        var b: UInt8 = 0
        guard read(STDIN_FILENO, &b, 1) == 1 else { return nil }
        if b == 0x0A { break }
        line.append(b)
    }
    return String(decoding: line, as: UTF8.self)
}

func emit(_ s: String) {
    FileHandle.standardOutput.write(Data((s + "\n").utf8))
}

while let line = readStdinLine() {
    // Only `tool_request` lines are answered; the agent's hello/status/text/
    // ready stream is the wire's telemetry, not the app's concern.
    guard let data = line.data(using: .utf8),
          let obj = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
          let t = obj["t"] as? String, t == "tool_request",
          let idx = (obj["idx"] as? NSNumber)?.intValue,
          let name = obj["name"] as? String else { continue }
    let answer = answers[name]
    let result: [String: Any] = [
        "t": "tool_result",
        "idx": idx,
        "ok": answer != nil,
        "s": answer ?? refusal,
    ]
    guard let rdata = try? JSONSerialization.data(withJSONObject: result, options: [.sortedKeys]),
          let json = String(data: rdata, encoding: .utf8) else { continue }
    emit(json)
}
"""#

        return template
            .replacingOccurrences(of: "__ANSWERS__", with: answersLiteral)
            .replacingOccurrences(of: "__REFUSAL__", with: refusalLiteral)
    }
}
