import Foundation

public enum FakeServerError: Error, Equatable, Sendable {
    case lineCountMismatch(capture: Int, sidecar: Int)
    case malformedCaptureLine(line: Int, content: String)
}

/// Generates the complete Swift source of a fake `ds4-server` from a committed
/// capture + sidecar. The fake validates its argv strictly, listens on `--port`,
/// prints the listening line to stderr (so the supervisor's ready detection works
/// against it), and replays the capture with sidecar-derived delays. `FAKE_SPEED`
/// env (0 = no delay) keeps integration tests fast; env is not argv, so argv
/// stays strict.
public enum FakeServerSource {

    public static func generate(capture: Data, sidecar: Data, engineArgv: [String]) throws -> String {
        let captureText = String(decoding: capture, as: UTF8.self)
        let sidecarText = String(decoding: sidecar, as: UTF8.self)

        var captureLines = captureText.split(separator: "\n", omittingEmptySubsequences: false)
        if captureLines.last == "" { captureLines.removeLast() }
        let stamps = sidecarText.split(separator: "\n", omittingEmptySubsequences: false)
            .compactMap { Int($0.trimmingCharacters(in: .whitespaces)) }

        guard stamps.count == captureLines.count else {
            throw FakeServerError.lineCountMismatch(capture: captureLines.count, sidecar: stamps.count)
        }

        // Validate every non-blank line, and build the replay list with per-line
        // delays (µs) derived from consecutive sidecar timestamps.
        var replay: [(Int, String)] = []
        var lastStamp = stamps.first ?? 0
        for (index, line) in captureLines.enumerated() {
            let trimmed = line.trimmingCharacters(in: .whitespacesAndNewlines)
            if trimmed.isEmpty { continue }
            guard trimmed.hasPrefix("data:") else {
                throw FakeServerError.malformedCaptureLine(line: index + 1, content: trimmed)
            }
            let delayMicros = max(0, (stamps[index] - lastStamp) / 1000)
            lastStamp = stamps[index]
            replay.append((delayMicros, String(line)))
        }

        let argvLiteral = engineArgv.map(swiftStringLiteral).joined(separator: ", ")
        let replayLiteral = replay
            .map { "    (\($0.0), \(swiftStringLiteral($0.1)))" }
            .joined(separator: ",\n")

        // Raw string template: `\(...)` and `\n` inside are literal for the
        // generated file; only the __ARGV__ / __REPLAY__ placeholders are filled.
        let template = #"""
import Foundation
import Darwin

// GENERATED by SwiftStarKit.FakeServerSource — do not hand-edit.
// Regenerate from the committed capture; a drift test pins this.

let expectedArgv: [String] = [__ARGV__]
let replay: [(Int, String)] = [
__REPLAY__
]

func validateArgv() -> Bool {
    let actual = Array(CommandLine.arguments.dropFirst())
    return actual == expectedArgv
}

if !validateArgv() {
    FileHandle.standardError.write(Data("fake ds4-server: argv mismatch; expected \(expectedArgv) got \(Array(CommandLine.arguments.dropFirst()))\n".utf8))
    exit(1)
}

guard let portIndex = CommandLine.arguments.firstIndex(of: "--port"),
      CommandLine.arguments.count > portIndex + 1,
      let port = Int(CommandLine.arguments[portIndex + 1]) else {
    FileHandle.standardError.write(Data("fake ds4-server: missing --port\n".utf8))
    exit(2)
}

let speed = Double(ProcessInfo.processInfo.environment["FAKE_SPEED"] ?? "1.0") ?? 1.0

final class ServerSocket {
    private let fd: Int32
    init(port: Int) throws {
        let s = socket(AF_INET, SOCK_STREAM, 0)
        guard s >= 0 else { throw NSError(domain: "fake", code: 1) }
        var opt: Int32 = 1
        setsockopt(s, SOL_SOCKET, SO_REUSEADDR, &opt, socklen_t(MemoryLayout<Int32>.size))
        var addr = sockaddr_in()
        addr.sin_family = sa_family_t(AF_INET)
        addr.sin_port = in_port_t(port).bigEndian
        addr.sin_addr.s_addr = inet_addr("127.0.0.1")
        let bindResult = withUnsafePointer(to: &addr) { ptr in
            ptr.withMemoryRebound(to: sockaddr.self, capacity: 1) {
                bind(s, $0, socklen_t(MemoryLayout<sockaddr_in>.size))
            }
        }
        guard bindResult == 0 else { close(s); throw NSError(domain: "fake", code: 2) }
        guard listen(s, 8) == 0 else { close(s); throw NSError(domain: "fake", code: 3) }
        self.fd = s
    }
    func accept() throws -> Client {
        let c = Darwin.accept(fd, nil, nil)
        guard c >= 0 else { throw NSError(domain: "fake", code: 4) }
        return Client(fd: c)
    }
}

final class Client {
    private let fd: Int32
    init(fd: Int32) { self.fd = fd }
    func write(_ s: String) throws {
        let bytes = Array(s.utf8)
        var offset = 0
        while offset < bytes.count {
            let written = bytes.withUnsafeBytes { raw -> Int in
                Darwin.write(fd, raw.baseAddress!.advanced(by: offset), bytes.count - offset)
            }
            if written <= 0 { throw NSError(domain: "fake", code: 5) }
            offset += written
        }
    }
    func close() { Darwin.close(fd) }
}

do {
    let server = try ServerSocket(port: port)
    FileHandle.standardError.write(Data("fake ds4-server: listening on http://127.0.0.1:\(port)\n".utf8))
    while true {
        let client = try server.accept()
        for (delay, line) in replay {
            if speed > 0 { usleep(useconds_t(Double(delay) / speed)) }
            try client.write(line + "\n")
        }
        try client.write("\n")
        client.close()
    }
} catch {
    FileHandle.standardError.write(Data("fake ds4-server: \(error)\n".utf8))
    exit(3)
}
"""#

        return template
            .replacingOccurrences(of: "__ARGV__", with: argvLiteral)
            .replacingOccurrences(of: "__REPLAY__", with: replayLiteral)
    }

    /// Escapes a string for embedding as a Swift string literal in the
    /// generated source (backslash, quote, newline, carriage return, tab,
    /// and any other ASCII control character).
    static func swiftStringLiteral(_ s: String) -> String {
        var out = "\""
        for scalar in s.unicodeScalars {
            switch scalar {
            case "\\": out += "\\\\"
            case "\"": out += "\\\""
            case "\n": out += "\\n"
            case "\r": out += "\\r"
            case "\t": out += "\\t"
            default:
                if scalar.isASCII, CharacterSet.controlCharacters.contains(UnicodeScalar(scalar.value)!) {
                    out += "\\u{\(String(scalar.value, radix: 16))}"
                } else {
                    out.unicodeScalars.append(scalar)
                }
            }
        }
        out += "\""
        return out
    }
}
